Repository wafflestudio/waffledotcom-web, pull requests merged in 2023-06, with the labels that each got.

#31 Feat/home main about
  components/Home/scroll.ts
  components/common/Header/Header.module.scss
  components/common/Header/Header.tsx
  components/common/Scroll/ScrollNavigator.module.scss
  components/common/Scroll/ScrollNavigator.tsx
  components/newHome/About/About.module.scss
  components/newHome/About/About.tsx
  components/newHome/Main/Main.module.scss
  components/newHome/Main/Main.tsx
  library/waffleScroll/README.md
  library/waffleScroll/index.ts
  library/waffleScroll/types.ts
  pages/newHome/Home.module.scss
  pages/newHome/index.tsx
  public/static/images/home/home_main_button.png
  public/static/images/logo/pupuri_logo.png
  public/static/images/logo/waffle_logo_title.png
  styles/font.scss
  styles/globals.css
Labels: new feature

#33 Feat/home service member
  components/newHome/Members/Members.module.scss
  components/newHome/Members/Members.tsx
  components/newHome/Services/Carousel.module.scss
  components/newHome/Services/Carousel.tsx
  components/newHome/Services/ProgressBox.module.scss
  components/newHome/Services/ProgressBox.tsx
  components/newHome/Services/Services.module.scss
  components/newHome/Services/Services.tsx
  pages/newHome/index.tsx
  public/static/images/newHome/arrow_icon.svg
  public/static/images/newHome/designers_icon.svg
  public/static/images/newHome/next_button_icon.svg
  public/static/images/newHome/phone_siksha.svg
  public/static/images/newHome/phone_snuboard.svg
  public/static/images/newHome/phone_snutt.svg
  public/static/images/newHome/play_button_icon.svg
  public/static/images/newHome/previous_button_icon.svg
  public/static/images/newHome/programmers_icon.svg
  public/static/images/newHome/progress_foreground_border.svg
  public/static/images/newHome/rookies_icon.svg
  public/static/images/newHome/stop_button_icon.svg
Labels: help wanted, new feature

#32 Feat/newhome-activity
  components/common/Header/Header.module.scss
  components/newHome/Activity/Activity.module.scss
  components/newHome/Activity/Activity.tsx
  package-lock.json
  package.json
  pages/newHome/index.tsx
  public/static/images/activity/activityImage1.png
  yarn.lock
Labels: new feature

#36 Refact/member page
  components/Member/Board/Board.module.scss
  components/Member/Board/Board.tsx
  components/Member/Board/Card/Card.module.scss
  components/Member/Board/Card/Card.tsx
  components/Member/Board/CustomScrollbarDiv/CustomScrollbarDiv.module.scss
  components/Member/Board/CustomScrollbarDiv/CustomScrollbarDiv.tsx
  components/Member/Board/Filter/Filter.module.scss
  components/Member/Board/Filter/Filter.tsx
  components/Member/Board/MemberCard/MemberCard.module.scss
  components/Member/Board/MemberCard/MemberCard.tsx
  components/Member/Board/Sidebar/Sidebar.module.scss
  components/Member/Board/Sidebar/Sidebar.tsx
  components/Member/Board/Sidebar/SidebarButtons.module.scss
  components/Member/Board/Sidebar/SidebarButtons.tsx
  components/Member/Board/members.json
  pages/member/Member.module.scss
  pages/member/index.tsx
  public/static/images/DefaultProfileImage.svg
  public/static/images/GithubSymbol.png
  public/static/images/arrow/down_arrow.svg
  public/static/images/arrow/up_arrow.svg
  public/static/images/check.svg
  public/static/images/githubSymbol.svg
  public/static/images/illustration/fufuri.svg
  styles/_position.scss
  styles/font.scss
Labels: new feature

#37 Hotfix/service old scroll
  README.md
  components/Service/Siksha/Siksha.tsx
  components/Service/Snuboard/Snuboard.tsx
  components/Service/Snutt/Snutt.tsx
  components/Service/serviceScroll.ts
  components/common/Header/Header.module.scss
  package-lock.json
  yarn.lock
Labels: bug
